apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db-statefulset
  template:
    metadata:
      labels:
        app: db-statefulset
    spec:
      containers:
        - name: postgres
          image: postgres:14.2-bullseye
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
      # TODO: Change to Persistent Volume
      volumes:
        - name: data
          emptyDir: {}
