apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  # type: ClusterIP
  # clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: db-statefulset
